---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: kubedoom
spec:
  hostNetwork: true
  serviceAccountName: kubedoom
  containers:
  - image: storaxdev/kubedoom:0.5.0
    name: kubedoom
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "800m"
    ports:
    - containerPort: 5900
      protocol: TCP
